### ISSUE TITLE
Porting to other AVR-based Arduino boards (Mega & Micro, based on Atmega2560 and Atmega32u4) and ARM-based Arduino boards (Zero & MKR1000, both based in Cortex-M3)

### ISSUE THREAD

**Issue by q2dg** [connornishijima/arduino-volume#4]
Could be it possible?
Thanks!!

**Comment by connornishijima** [comment]
Though it doesn't work yet for Mega (Troubleshooting this today) I've gotten it to work with an ATMEGA32u4 by having it use pins 9 and 10 instead. This is because Timer0 is tied to these pins on that IC.

**Comment by connornishijima** [comment]
I've just added direct support for 2560 and 32u4 in [version 1.1.0](https://github.com/connornishijima/arduino-volume/releases/tag/1.1.0)! :) [DETAILS HERE](https://hackaday.io/project/11957-8-bit-component-less-volume-control-for-arduino/log/39957-people-were-ready-for-this)

However, I don't actually own any of the ARM 'duino's, so I can't test them myself at this time. Currently working on ATtiny*5 support now. :)
